language: cpp
cache: ccache
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - chmod +x ./test.sh

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - ./test.sh
